In [11]:
#Installing selenium
!pip install selenium
!pip install webdriver_manager

Requirement already satisfied: selenium in c:\users\dc\anaconda3\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\dc\anaconda3\lib\site-packages (from selenium) (1.25.8)
Requirement already satisfied: webdriver_manager in c:\users\dc\anaconda3\lib\site-packages (3.2.2)
Requirement already satisfied: crayons in c:\users\dc\anaconda3\lib\site-packages (from webdriver_manager) (0.4.0)
Requirement already satisfied: requests in c:\users\dc\anaconda3\lib\site-packages (from webdriver_manager) (2.22.0)
Requirement already satisfied: configparser in c:\users\dc\anaconda3\lib\site-packages (from webdriver_manager) (5.0.1)
Requirement already satisfied: colorama in c:\users\dc\anaconda3\lib\site-packages (from crayons->webdriver_manager) (0.4.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\dc\anaconda3\lib\site-packages (from requests->webdriver_manager) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\dc\anaconda3\lib\site-packages (from requests->webdriver_manager) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\dc\anaconda3\lib\site-packages (from requests->webdriver_manager) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dc\anaconda3\lib\site-packages (from requests->webdriver_manager) (2019.11.28)

In [12]:
#importing libraries
import pandas as pd
import numpy as np

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium.common.exceptions import NoSuchElementException

from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException
from webdriver_manager.chrome import ChromeDriverManager
import time

#Using proxy chrome driver
driver = webdriver.Chrome('C:/Users/DC/Desktop/chromedriver.exe')
driver.maximize_window()

#Data extraction,collection and dataframe creation
final_df = pd.DataFrame()

for i in range(0, 101,25):
    print(i)
    driver.get(f'https://www.monsterindia.com/srp/results?start={i}&sort=1&limit=25&query=Data%20Scientist&locations=Delhi')
    
    jobs = [i.text for i in driver.find_elements_by_xpath("//*[contains(@class, 'medium')]") if len(i.text)]
    company = [i.text for i in driver.find_elements_by_xpath("//*[contains(@class, 'company-name')]") if len(i.text)]
    loc = [i.text for i in driver.find_elements_by_xpath("//span[contains(@class, 'loc')]")][1:-1]
    loc = [loc[k:k+3] for k in range(0, len(loc), 3)]

    df = pd.DataFrame(loc, columns=['loc', 'exp', 'salary'])
    df['role'] = jobs
    df['company'] = company
    df = df[['role', 'company', 'loc', 'exp', 'salary']]
    
    final_df = pd.concat([final_df, df])
final_df = final_df.reset_index(drop=True)

0
25
50
75
100

In [13]:
final_df

,role,company,loc,exp,salary
0,Data Analyst / Fresher / Data Scientist / Grad...,Structured Learning Assistance Consultants Ind...,"Delhi, Gurgaon / Gurugram",0-5 Years,Not Specified
1,Data Analyst – Fresher – Data Scientist – Any ...,Structured Learning Assistance Consultants Ind...,"Delhi, Noida",0-5 Years,Not Specified
2,Data Analyst / Fresher / Data Scientist / Grad...,Structured Learning Assistance Consultants Ind...,"Delhi, Ghaziabad",0-5 Years,Not Specified
3,Data Analyst – Fresher – Data Scientist – Grad...,Structured Learning Assistance Consultants Ind...,"Delhi, Noida",0-5 Years,Not Specified
4,Data Analyst – Fresher – Data Scientist – Grad...,Structured Learning Assistance Consultants Ind...,"Delhi, Gurgaon / Gurugram",0-5 Years,Not Specified
5,DATA ANALYST – FRESHER – DATA SCIENTIST – SAS ...,Structured Learning Assistance Consultants Ind...,"Delhi, Noida",0-5 Years,Not Specified
6,Data Scientist,Talent Corner Hr Services Private Limited,"Pune, Delhi NCR",3-6 Years,Not Specified
7,Data Scientist - 11,Accenture,"Delhi, Mumbai",0-3 Years,Not Specified
8,Data Scientist - 09,Accenture,"Delhi, Mumbai",3-6 Years,Not Specified
9,Data Scientist - 09,Accenture,"Delhi, Mumbai",3-6 Years,Not Specified
10,Data Scientist - 11,Accenture,"Delhi, Mumbai",0-3 Years,Not Specified
11,Data Scientist - Gurgaon || Experience 5 - 7 y...,WNS Global Services Private Limited,"Delhi, Delhi NCR",,"6,00,000-9,50,000 INR"
12,Manager - Predective Modeler,Genpact,Gurgaon / Gurugram,5-8 Years,Not Specified
13,Assistant Manager - Data Scientist,Genpact,Gurgaon / Gurugram,,Not Specified
14,Job Opportunity || Sr. Data Scientist || 6 Mon...,Select Source International Private Limited,Gurgaon / Gurugram,5-10 Years,Not Specified
15,Business Intelligence Engineer,Amazon,Gurgaon / Gurugram,3-6 Years,Not Specified
16,Manager - Data Science,Genpact,Gurgaon / Gurugram,,Not Specified
17,"AWS, Pyspark - Gurgaon",Magna Infotech Limited,"Gurgaon / Gurugram, Noida",5-15 Years,Not Specified
18,Job Opportunity || Sr. Data Scientist || 6 Mon...,Select Source International Private Limited,Gurgaon / Gurugram,5-10 Years,"12,00,000-20,00,000 INR"
19,Assistant Vice President - Data Scientist,Genpact,Gurgaon / Gurugram,,Not Specified
20,Data Scientist Senior,ANI Calls India Private Limited,"Noida, India",5-8 Years,"8,00,000-14,00,000 INR"
21,Data Scientist,Globallogic Technologies Limited,Noida,3-8 Years,Not Specified
22,Manager - Data Scientist,Genpact,"Noida, India",,Not Specified
23,SAS grid consultant,ANI Calls India Private Limited,"Noida, India",6-8 Years,"8,00,000-16,00,000 INR"
24,AI / ML Data Scientist - Democratize commerce ...,CareerXperts Consulting,Noida,2-7 Years,Not Specified
25,Analyst - Datacentre Services,Coforge,"Noida, India",,Not Specified
26,Data Scientist,Talent Corner Hr Services Private Limited,"Vadodara, Chandigarh",4-8 Years,Not Specified

In [15]:
df.to_csv('Monster-DS-delhi.csv',index=False,encoding='utf-8')